name: Node.js CI
on:
  push:
    branches: [ master ] #监听master分支的push事件
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest #指定运行环境为最新的Ubuntu版本
    strategy:
      matrix:
        node-version: [15.9.0] #指定node版本
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} #使用action安装node环境
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install express
    - run: npm install fs
    - run: npm install body-parser
    - run: nodejs app.js 
